In [71]:
import pandas as pd
from sklearn.svm import LinearSVC
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import numpy as np

In [72]:
df1 = pd.read_csv('CTU-IoT-Malware-Capture-1-1conn.log.labeled.csv',sep = '|')

In [73]:
df1.head()

,ts,uid,id.orig_h,id.orig_p,id.resp_h,id.resp_p,proto,service,duration,orig_bytes,...,local_resp,missed_bytes,history,orig_pkts,orig_ip_bytes,resp_pkts,resp_ip_bytes,tunnel_parents,label,detailed-label
0,1.525880e+09,CUmrqr4svHuSXJy5z7,192.168.100.103,51524.0,65.127.233.163,23.0,tcp,-,2.999051,0,...,-,0.0,S,3.0,180.0,0.0,0.0,-,Malicious,PartOfAHorizontalPortScan
1,1.525880e+09,CH98aB3s1kJeq6SFOc,192.168.100.103,56305.0,63.150.16.171,23.0,tcp,-,-,-,...,-,0.0,S,1.0,60.0,0.0,0.0,-,Malicious,PartOfAHorizontalPortScan
2,1.525880e+09,C3GBTkINvXNjVGtN5,192.168.100.103,41101.0,111.40.23.49,23.0,tcp,-,-,-,...,-,0.0,S,1.0,60.0,0.0,0.0,-,Malicious,PartOfAHorizontalPortScan
3,1.525880e+09,CDe43c1PtgynajGI6,192.168.100.103,60905.0,131.174.215.147,23.0,tcp,-,2.998796,0,...,-,0.0,S,3.0,180.0,0.0,0.0,-,Malicious,PartOfAHorizontalPortScan
4,1.525880e+09,CJaDcG3MZzvf1YVYI4,192.168.100.103,44301.0,91.42.47.63,23.0,tcp,-,-,-,...,-,0.0,S,1.0,60.0,0.0,0.0,-,Malicious,PartOfAHorizontalPortScan

In [74]:
df2 = pd.read_csv('CTU-IoT-Malware-Capture-20-1conn.log.labeled.csv',sep='|')
df3 = pd.read_csv('CTU-IoT-Malware-Capture-21-1conn.log.labeled.csv',sep='|')
df4 = pd.read_csv('CTU-IoT-Malware-Capture-3-1conn.log.labeled.csv',sep='|')
df5 = pd.read_csv('CTU-IoT-Malware-Capture-34-1conn.log.labeled.csv',sep='|')
df6 = pd.read_csv('CTU-IoT-Malware-Capture-35-1conn.log.labeled.csv',sep='|')
df7 = pd.read_csv('CTU-IoT-Malware-Capture-42-1conn.log.labeled.csv',sep='|')
df8 = pd.read_csv('CTU-IoT-Malware-Capture-48-1conn.log.labeled.csv',sep='|')
df9 = pd.read_csv('CTU-IoT-Malware-Capture-60-1conn.log.labeled.csv',sep='|')
df10 = pd.read_csv('CTU-IoT-Malware-Capture-9-1conn.log.labeled.csv',sep='|')

C:\Users\Rohit\AppData\Local\Temp\ipykernel_34156\291993118.py:7: DtypeWarning: Columns (8,9,10) have mixed types. Specify dtype option on import or set low_memory=False.
  df8 = pd.read_csv('CTU-IoT-Malware-Capture-48-1conn.log.labeled.csv',sep='|')

In [75]:
df = pd.concat([df1,df2,df3,df4,df5,df6,df7,df8,df9,df10],axis = 0)

In [76]:
df=df[10000001:15000001]

In [77]:

del df1
del df2
del df3
del df4
del df5
del df6
del df7
del df8
del df9
del df10

In [78]:
df.head()

,ts,uid,id.orig_h,id.orig_p,id.resp_h,id.resp_p,proto,service,duration,orig_bytes,...,local_resp,missed_bytes,history,orig_pkts,orig_ip_bytes,resp_pkts,resp_ip_bytes,tunnel_parents,label,detailed-label
8805510,1.545473e+09,CmKKW74fdMB0qbO02i,192.168.1.196,56991.0,216.18.168.16,80.0,tcp,-,0.997943,0,...,-,0.0,I,3.0,120.0,0.0,0.0,-,Malicious DDoS,NaN
8805511,1.545473e+09,CmGWZm1bSWpLAqDuqc,192.168.1.196,52425.0,216.18.168.16,80.0,tcp,-,4.509697,0,...,-,0.0,I,2.0,80.0,0.0,0.0,-,Malicious DDoS,NaN
8805512,1.545473e+09,C3D4v44xBvTxbBPv1,192.168.1.196,20169.0,216.18.168.16,80.0,tcp,-,4.921978,0,...,-,0.0,I,2.0,80.0,0.0,0.0,-,Malicious DDoS,NaN
8805513,1.545473e+09,CsfeCk18lBaz8UMgg,192.168.1.196,13585.0,216.18.168.16,80.0,tcp,-,4.735055,0,...,-,0.0,I,3.0,120.0,0.0,0.0,-,Malicious DDoS,NaN
8805514,1.545473e+09,C51OXU3Yk1g85wJMZ,192.168.1.196,1896.0,216.18.168.16,80.0,tcp,-,4.382480,0,...,-,0.0,I,6.0,240.0,0.0,0.0,-,Malicious DDoS,NaN

In [79]:
df.replace('-', np.nan, inplace=True)

In [80]:
df.isnull().sum()

ts                      0
uid                     0
id.orig_h               0
id.orig_p               0
id.resp_h               0
id.resp_p               0
proto                   0
service           4998091
duration           806455
orig_bytes         806455
resp_bytes         806455
conn_state              0
local_orig        5000000
local_resp        5000000
missed_bytes            0
history              2505
orig_pkts               0
orig_ip_bytes           0
resp_pkts               0
resp_ip_bytes           0
tunnel_parents    5000000
label                   0
detailed-label    4998320
dtype: int64

In [81]:
df.shape

(5000000, 23)

In [82]:
df['label'].unique()

array(['Malicious   DDoS', 'Benign', 'Malicious   C&C',
       'Malicious   FileDownload',
       'Malicious   PartOfAHorizontalPortScan', 'Malicious   Attack'],
      dtype=object)

In [83]:
df['service'].unique()

array([nan, 'dns', 'http', 'ssl', 'dhcp'], dtype=object)

In [84]:
df['history'].unique()

array(['I', 'S', 'Dd', 'SI', 'D', 'Sr', nan, 'ShADdfFa', 'ShADadFf',
       'ShAfFa', 'ShAdfFa', 'ShwA', 'ShAdaDR', 'ShADdfF', 'ShADdattFfR',
       'F', 'ShwAr', 'ShADdf', 'ShAdDafr', 'ShAr', 'ShAdDaTR', 'ShAfF',
       'ShAfdtF', 'ShADdFaf', 'ShADdFf', 'ShAdfr', 'ShADdtatFfR',
       'ShAdDaFRR', 'ShAdDaR', 'Dr', 'R', 'ShAF', 'ShAdDaRRR',
       'ShAdDaTRf', 'HaDdAr', 'ShADad', 'ShADadttFf', 'ShADadRf',
       'ShAdfDr', 'ShAdDaf', 'ShAdDaft', 'DdA', 'ShADdaf', 'ShAfdtDr',
       'ShADadtFf', 'ShADadf', 'Aa', 'DaFfA', 'DdAa', 'ShADadttfF',
       'ShADadfF', 'ShAdDafR', 'ShAdr', 'DdAaFf', 'SaR', 'ShAdDaFR',
       'ShAfr', 'ShR', 'ShAdFaRf', 'ShAdDafF', 'ShAfFr', 'ShAdDaTFf',
       'ShAaww', 'ShAaw', 'ShAdDaTfr', 'ShAdDaRr', 'ShAdDaTfRr',
       'ShAfdtFa', 'ShAFr', 'ShAdDaRR', 'ShArr', 'ShAdDR', 'ShAdDatRRR',
       'ShAdDaFf', 'ShADadfr', 'ShAdDatR', 'ShAdDaTRft', 'ShAdDaTTRf',
       'ShAdDaTfR'], dtype=object)

In [85]:
df = pd.get_dummies(data = df, columns=['proto', 'conn_state', 'service'],drop_first=True)
df['history'] = pd.factorize(df['history'])[0] + 1

In [86]:
df['duration'] = df['duration'].astype('float')
df['orig_bytes'] = df['orig_bytes'].astype('float')
df['resp_bytes'] = df['resp_bytes'].astype('float')

In [87]:
desired_value = 'Benign'

df['label'] = [1 if x == desired_value else 0 for x in df['label']]

In [88]:
df['label'].sample(25)

533877      0
2574833     0
1824115     0
975009      0
1519242     0
1296037     0
1441911     0
9035664     1
9136082     1
8838166     0
66190       0
2708685     0
10075493    1
10430984    1
3160099     0
2267125     0
3062096     0
10035271    1
9503954     1
3224227     0
9472525     1
1872123     0
2514717     0
2744665     0
2192784     0
Name: label, dtype: int64

In [89]:
df = df.drop(columns=['uid', 'local_orig', 'local_resp', 'tunnel_parents', 'detailed-label', 'id.orig_h', 'id.resp_h'])

In [90]:
df = df.fillna(0)

In [91]:
df.head()

,ts,id.orig_p,id.resp_p,duration,orig_bytes,resp_bytes,missed_bytes,history,orig_pkts,orig_ip_bytes,...,conn_state_RSTRH,conn_state_S0,conn_state_S1,conn_state_S2,conn_state_S3,conn_state_SF,conn_state_SH,service_dns,service_http,service_ssl
8805510,1.545473e+09,56991.0,80.0,0.997943,0.0,0.0,0.0,1,3.0,120.0,...,False,False,False,False,False,False,False,False,False,False
8805511,1.545473e+09,52425.0,80.0,4.509697,0.0,0.0,0.0,1,2.0,80.0,...,False,False,False,False,False,False,False,False,False,False
8805512,1.545473e+09,20169.0,80.0,4.921978,0.0,0.0,0.0,1,2.0,80.0,...,False,False,False,False,False,False,False,False,False,False
8805513,1.545473e+09,13585.0,80.0,4.735055,0.0,0.0,0.0,1,3.0,120.0,...,False,False,False,False,False,False,False,False,False,False
8805514,1.545473e+09,1896.0,80.0,4.382480,0.0,0.0,0.0,1,6.0,240.0,...,False,False,False,False,False,False,False,False,False,False

In [92]:
df = df.replace(False,0)
df = df.replace(True,1)

In [93]:
df.head()

,ts,id.orig_p,id.resp_p,duration,orig_bytes,resp_bytes,missed_bytes,history,orig_pkts,orig_ip_bytes,...,conn_state_RSTRH,conn_state_S0,conn_state_S1,conn_state_S2,conn_state_S3,conn_state_SF,conn_state_SH,service_dns,service_http,service_ssl
8805510,1.545473e+09,56991.0,80.0,0.997943,0.0,0.0,0.0,1,3.0,120.0,...,0,0,0,0,0,0,0,0,0,0
8805511,1.545473e+09,52425.0,80.0,4.509697,0.0,0.0,0.0,1,2.0,80.0,...,0,0,0,0,0,0,0,0,0,0
8805512,1.545473e+09,20169.0,80.0,4.921978,0.0,0.0,0.0,1,2.0,80.0,...,0,0,0,0,0,0,0,0,0,0
8805513,1.545473e+09,13585.0,80.0,4.735055,0.0,0.0,0.0,1,3.0,120.0,...,0,0,0,0,0,0,0,0,0,0
8805514,1.545473e+09,1896.0,80.0,4.382480,0.0,0.0,0.0,1,6.0,240.0,...,0,0,0,0,0,0,0,0,0,0

In [94]:
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score

In [95]:
y = df['label']

In [96]:
X = df.drop(columns = ['label'])

In [97]:
y.sample(20)

676826     0
9906178    1
422465     0
1104387    0
774221     0
3186595    0
1706206    0
2872778    0
2888113    0
9549905    1
1484779    0
2325230    0
1492708    0
9241132    1
1912654    0
9565339    1
2611800    0
2985538    0
9712259    1
2793778    0
Name: label, dtype: int64

In [98]:
X.head()

,ts,id.orig_p,id.resp_p,duration,orig_bytes,resp_bytes,missed_bytes,history,orig_pkts,orig_ip_bytes,...,conn_state_RSTRH,conn_state_S0,conn_state_S1,conn_state_S2,conn_state_S3,conn_state_SF,conn_state_SH,service_dns,service_http,service_ssl
8805510,1.545473e+09,56991.0,80.0,0.997943,0.0,0.0,0.0,1,3.0,120.0,...,0,0,0,0,0,0,0,0,0,0
8805511,1.545473e+09,52425.0,80.0,4.509697,0.0,0.0,0.0,1,2.0,80.0,...,0,0,0,0,0,0,0,0,0,0
8805512,1.545473e+09,20169.0,80.0,4.921978,0.0,0.0,0.0,1,2.0,80.0,...,0,0,0,0,0,0,0,0,0,0
8805513,1.545473e+09,13585.0,80.0,4.735055,0.0,0.0,0.0,1,3.0,120.0,...,0,0,0,0,0,0,0,0,0,0
8805514,1.545473e+09,1896.0,80.0,4.382480,0.0,0.0,0.0,1,6.0,240.0,...,0,0,0,0,0,0,0,0,0,0

In [99]:
del df

In [100]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [101]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [102]:
import lightgbm as lgb
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


params = {
    'objective': 'binary',
    'boosting_type': 'gbdt',
    'metric': 'binary_logloss',
    'num_leaves': 31,
    'learning_rate': 0.05,
    'feature_fraction': 0.9
}

In [103]:
train_data = lgb.Dataset(X_train, label=y_train)


model = lgb.train(params, train_data, num_boost_round=100)


y_pred = model.predict(X_test)


y_pred_binary = (y_pred > 0.5).astype(int)


accuracy = accuracy_score(y_test, y_pred_binary)

[LightGBM] [Info] Number of positive: 1239750, number of negative: 2760250
[LightGBM] [Warning] Auto-choosing row-wise multi-threading, the overhead of testing was 0.064114 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 922
[LightGBM] [Info] Number of data points in the train set: 4000000, number of used features: 25
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.309937 -> initscore=-0.800412
[LightGBM] [Info] Start training from score -0.800412

In [104]:
print("Accuracy:", accuracy)

Accuracy: 0.999998

In [105]:
from sklearn.metrics import classification_report


report = classification_report(y_test, y_pred_binary)


print(report)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00    690259
           1       1.00      1.00      1.00    309741

    accuracy                           1.00   1000000
   macro avg       1.00      1.00      1.00   1000000
weighted avg       1.00      1.00      1.00   1000000