In [1]:
import pandas as pd
from sklearn.svm import LinearSVC
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import numpy as np

In [2]:
df1 = pd.read_csv('CTU-IoT-Malware-Capture-1-1conn.log.labeled.csv',sep = '|')

In [3]:
df1.head()

,ts,uid,id.orig_h,id.orig_p,id.resp_h,id.resp_p,proto,service,duration,orig_bytes,...,local_resp,missed_bytes,history,orig_pkts,orig_ip_bytes,resp_pkts,resp_ip_bytes,tunnel_parents,label,detailed-label
0,1.525880e+09,CUmrqr4svHuSXJy5z7,192.168.100.103,51524.0,65.127.233.163,23.0,tcp,-,2.999051,0,...,-,0.0,S,3.0,180.0,0.0,0.0,-,Malicious,PartOfAHorizontalPortScan
1,1.525880e+09,CH98aB3s1kJeq6SFOc,192.168.100.103,56305.0,63.150.16.171,23.0,tcp,-,-,-,...,-,0.0,S,1.0,60.0,0.0,0.0,-,Malicious,PartOfAHorizontalPortScan
2,1.525880e+09,C3GBTkINvXNjVGtN5,192.168.100.103,41101.0,111.40.23.49,23.0,tcp,-,-,-,...,-,0.0,S,1.0,60.0,0.0,0.0,-,Malicious,PartOfAHorizontalPortScan
3,1.525880e+09,CDe43c1PtgynajGI6,192.168.100.103,60905.0,131.174.215.147,23.0,tcp,-,2.998796,0,...,-,0.0,S,3.0,180.0,0.0,0.0,-,Malicious,PartOfAHorizontalPortScan
4,1.525880e+09,CJaDcG3MZzvf1YVYI4,192.168.100.103,44301.0,91.42.47.63,23.0,tcp,-,-,-,...,-,0.0,S,1.0,60.0,0.0,0.0,-,Malicious,PartOfAHorizontalPortScan

In [4]:
df2 = pd.read_csv('CTU-IoT-Malware-Capture-20-1conn.log.labeled.csv',sep='|')
df3 = pd.read_csv('CTU-IoT-Malware-Capture-21-1conn.log.labeled.csv',sep='|')
df4 = pd.read_csv('CTU-IoT-Malware-Capture-3-1conn.log.labeled.csv',sep='|')
df5 = pd.read_csv('CTU-IoT-Malware-Capture-34-1conn.log.labeled.csv',sep='|')
df6 = pd.read_csv('CTU-IoT-Malware-Capture-35-1conn.log.labeled.csv',sep='|')
df7 = pd.read_csv('CTU-IoT-Malware-Capture-42-1conn.log.labeled.csv',sep='|')
df8 = pd.read_csv('CTU-IoT-Malware-Capture-48-1conn.log.labeled.csv',sep='|')
df9 = pd.read_csv('CTU-IoT-Malware-Capture-60-1conn.log.labeled.csv',sep='|')
df10 = pd.read_csv('CTU-IoT-Malware-Capture-9-1conn.log.labeled.csv',sep='|')

C:\Users\Harshneel\AppData\Local\Temp\ipykernel_12712\291993118.py:7: DtypeWarning: Columns (8,9,10) have mixed types. Specify dtype option on import or set low_memory=False.
  df8 = pd.read_csv('CTU-IoT-Malware-Capture-48-1conn.log.labeled.csv',sep='|')

In [5]:
dff = pd.concat([df1,df2,df3,df4,df5,df6,df7,df8,df9,df10],axis = 0)

In [6]:
df = dff[:5000000]

In [7]:
del dff
del df1
del df2
del df3
del df4
del df5
del df6
del df7
del df8
del df9
del df10

In [8]:
df.head()

,ts,uid,id.orig_h,id.orig_p,id.resp_h,id.resp_p,proto,service,duration,orig_bytes,...,local_resp,missed_bytes,history,orig_pkts,orig_ip_bytes,resp_pkts,resp_ip_bytes,tunnel_parents,label,detailed-label
0,1.525880e+09,CUmrqr4svHuSXJy5z7,192.168.100.103,51524.0,65.127.233.163,23.0,tcp,-,2.999051,0,...,-,0.0,S,3.0,180.0,0.0,0.0,-,Malicious,PartOfAHorizontalPortScan
1,1.525880e+09,CH98aB3s1kJeq6SFOc,192.168.100.103,56305.0,63.150.16.171,23.0,tcp,-,-,-,...,-,0.0,S,1.0,60.0,0.0,0.0,-,Malicious,PartOfAHorizontalPortScan
2,1.525880e+09,C3GBTkINvXNjVGtN5,192.168.100.103,41101.0,111.40.23.49,23.0,tcp,-,-,-,...,-,0.0,S,1.0,60.0,0.0,0.0,-,Malicious,PartOfAHorizontalPortScan
3,1.525880e+09,CDe43c1PtgynajGI6,192.168.100.103,60905.0,131.174.215.147,23.0,tcp,-,2.998796,0,...,-,0.0,S,3.0,180.0,0.0,0.0,-,Malicious,PartOfAHorizontalPortScan
4,1.525880e+09,CJaDcG3MZzvf1YVYI4,192.168.100.103,44301.0,91.42.47.63,23.0,tcp,-,-,-,...,-,0.0,S,1.0,60.0,0.0,0.0,-,Malicious,PartOfAHorizontalPortScan

In [9]:
df.replace('-', np.nan, inplace=True)

In [10]:
df.isnull().sum()

ts                      0
uid                     0
id.orig_h               0
id.orig_p               0
id.resp_h               0
id.resp_p               0
proto                   0
service           4985873
duration          2803111
orig_bytes        2803111
resp_bytes        2803111
conn_state              0
local_orig        5000000
local_resp        5000000
missed_bytes            0
history             19399
orig_pkts               0
orig_ip_bytes           0
resp_pkts               0
resp_ip_bytes           0
tunnel_parents    5000000
label                   0
detailed-label    4308919
dtype: int64

In [11]:
df.shape

(5000000, 23)

In [12]:
df['label'].unique()

array(['Malicious', 'Benign', 'Malicious   C&C',
       'Malicious   PartOfAHorizontalPortScan', 'Malicious   DDoS',
       'Malicious   Attack'], dtype=object)

In [13]:
df['service'].unique()

array([nan, 'http', 'dhcp', 'ssh', 'dns', 'irc'], dtype=object)

In [14]:
df['history'].unique()

array(['S', 'Sr', 'D', 'Dd', nan, 'R', 'ShAdaFr', 'ShAfFa', 'ShAdfFa',
       'ShAF', '^r', 'ShADadfR', 'ShA', 'ShADr', 'ShADFr', 'ShAdDafF',
       'ShAr', 'ShADafr', 'ShADarfF', 'ShAFr', 'ShAdDaFf', 'ShAdDaTFf',
       'ShADF', 'ShAdDaTF', 'SaR', 'ShAdDtafF', 'ShADadRf', 'ShAdDaFr',
       'ShAdDaFRf', 'ShADadfF', 'ShADFadfRR', 'ShADafF', 'ShAdDatFf',
       'ShADadR', 'ShAdtDaFrR', 'ShAdDatFr', 'ShAdtDaFr', 'ShAdDatFrR',
       'ShAdDaFrR', 'ShAdDatfF', 'D^', 'ShADdfFa', 'ShAdDfFr',
       'ShAdDafFr', 'ShADrfR', 'ShADdafR', 'ShAFf', 'ShADaF', 'ShAFa',
       'ShAdDaF', 'ShAdF', 'ShAdDafrR', 'ShAdDafFrR', 'ShADfdtR',
       'ShAdDarfR', 'SahAdDrfR', 'Fr', 'ShAdDatrfR', 'ShADar', 'ShAdDr',
       'HaDdR', 'ShADadFf', 'ShAdDaTfF', 'ShAdDTafF', 'ShAdDaTFfR',
       'ShAdDaftF', 'ShAdFaf', 'ShAFfR', 'ShAdDafrFr', 'ShADfFr',
       'ShADfrFr', 'ShrA', 'F', 'ShADafdtF', 'ShAdr', 'ShAdDtaFr',
       'ShAdDFar', 'ShAdDarr', 'ShAdDaFfr', 'HaDdAfF', 'ShAdDaFfR',
       'HaFfA', 'ShAdDafFR', 'Ar', 'ShAdDaFRfR', 'ShAdDaFTf', 'ShADdfR',
       'FfA', 'Fa', 'HaDdAFf', 'FaAr', 'ShAFafR', 'HaDdAFTf',
       'ShAdDaftFR', 'ShADfaF', '^hADafF', 'ShADfFa', 'ShAdDFfR',
       'ShAfdtDFr', 'ShAdfDFr', 'HaR', '^aR', 'ShADfFrr', 'ShAdDfFa',
       'ShAadDfF', 'ShADfdtFaR', 'ShAdDar', 'FaR', 'ShAFdRfR',
       'ShAdDafFrr', 'Ffa', 'ShAdtDafF', 'ShAdDaFRRf', 'ShAdDtafFr',
       'ShAdDafr', 'HaADdFf', 'HaDdTAFf', 'HafFr', 'ShADfR', '^hADadfR',
       '^hA', 'ShAFdfRt', '^hADFr', 'ShADfrF', 'ShADfF', '^hADr', '^d',
       'D^d', 'ShADaCGdtfF', 'ShADaCGr', 'ShADCaGcgd', '^dDA',
       'ShADCaGdfF', 'ShADaCGcgdF', 'ShADaCGdt', 'ShADadfrr', 'DdA',
       'ShAadDr', 'ShADFfR', 'ShADad', 'ShADFa', 'ShR', '^aA', 'ShADFar',
       'ShAdDaFRRfR', 'ShAdDaR', 'ShAdDaFRRRf', 'ShADFaR', 'ShArR',
       'ShADadFfR', 'ShAa', 'ShAdDaFT', 'ShAdDFf', 'ShAdDaFRR',
       'ShAdDaFR', 'ShAdDaFRfRR', 'ShAdDatR', 'ShADFfa', 'ShADaR',
       'ShAafF', 'ShADa', 'ShAdDFaf', 'ShAdDaFfRR', 'ShAdDtaFf',
       'ShAadDFf', 'ShAadDFRf', 'ShAdDaTFRf', 'ShAadDFR', 'SahAdDFRf',
       'SahAdDFf', 'DFafA', 'SahAdDtFf', 'SahAdDF', 'ShADFadfR',
       'ShAdDaFRr', 'ShADadttcfF', 'ShADadtcfF', 'ShADadtctfF', 'DdAtaFf',
       'ShAdDaf', 'ShADacdtfF', 'ShADadtctfFR', 'ShAdDaft', 'ShADadttfF',
       'ShAdfDr', 'ShAfdtDr', 'ShAdDatf', 'ShAdDatfr', 'ShDadAf', 'ShAdD',
       'ShADadf', 'ShAdDfr', 'ShAD', 'C', 'CCCC', 'CCC', 'ShAdDa',
       'DdAaFf', 'ShADadtfF', 'ShAdDaTR', 'ShAfF', 'ShAaw', 'ShAdDaTRr',
       'ShAdfDF', 'ShwA', 'ShAdfr', 'ShAdDaTFR', 'ShwAr', 'ShAdDaRr'],
      dtype=object)

In [16]:
df = pd.get_dummies(data = df, columns=['proto', 'conn_state', 'service'],drop_first=True)
df['history'] = pd.factorize(df['history'])[0] + 1

In [17]:
df['duration'] = df['duration'].astype('float')
df['orig_bytes'] = df['orig_bytes'].astype('float')
df['resp_bytes'] = df['resp_bytes'].astype('float')

In [18]:
desired_value = 'Benign'

df['label'] = [1 if x == desired_value else 0 for x in df['label']]

In [19]:
df['label'].sample(25)

3061231    1
3089124    1
3532953    1
668533     1
861861     1
710403     1
804516     1
768470     1
654674     0
2446429    1
1670506    1
2232237    1
3682475    1
2773784    1
1330214    1
700145     1
382080     0
3380326    1
510862     1
929897     1
1980782    1
3511993    1
3620169    1
2809362    1
39772      0
Name: label, dtype: int64

In [20]:
df = df.drop(columns=['uid', 'local_orig', 'local_resp', 'tunnel_parents', 'detailed-label', 'id.orig_h', 'id.resp_h'])

In [21]:
df = df.fillna(0)

In [22]:
df.head()

,ts,id.orig_p,id.resp_p,duration,orig_bytes,resp_bytes,missed_bytes,history,orig_pkts,orig_ip_bytes,...,conn_state_S1,conn_state_S2,conn_state_S3,conn_state_SF,conn_state_SH,conn_state_SHR,service_dns,service_http,service_irc,service_ssh
0,1.525880e+09,51524.0,23.0,2.999051,0.0,0.0,0.0,1,3.0,180.0,...,False,False,False,False,False,False,False,False,False,False
1,1.525880e+09,56305.0,23.0,0.000000,0.0,0.0,0.0,1,1.0,60.0,...,False,False,False,False,False,False,False,False,False,False
2,1.525880e+09,41101.0,23.0,0.000000,0.0,0.0,0.0,1,1.0,60.0,...,False,False,False,False,False,False,False,False,False,False
3,1.525880e+09,60905.0,23.0,2.998796,0.0,0.0,0.0,1,3.0,180.0,...,False,False,False,False,False,False,False,False,False,False
4,1.525880e+09,44301.0,23.0,0.000000,0.0,0.0,0.0,1,1.0,60.0,...,False,False,False,False,False,False,False,False,False,False

In [25]:
df = df.replace(False,0)
df = df.replace(True,1)

In [26]:
df.head()

,ts,id.orig_p,id.resp_p,duration,orig_bytes,resp_bytes,missed_bytes,history,orig_pkts,orig_ip_bytes,...,conn_state_S1,conn_state_S2,conn_state_S3,conn_state_SF,conn_state_SH,conn_state_SHR,service_dns,service_http,service_irc,service_ssh
0,1.525880e+09,51524.0,23.0,2.999051,0.0,0.0,0.0,1,3.0,180.0,...,0,0,0,0,0,0,0,0,0,0
1,1.525880e+09,56305.0,23.0,0.000000,0.0,0.0,0.0,1,1.0,60.0,...,0,0,0,0,0,0,0,0,0,0
2,1.525880e+09,41101.0,23.0,0.000000,0.0,0.0,0.0,1,1.0,60.0,...,0,0,0,0,0,0,0,0,0,0
3,1.525880e+09,60905.0,23.0,2.998796,0.0,0.0,0.0,1,3.0,180.0,...,0,0,0,0,0,0,0,0,0,0
4,1.525880e+09,44301.0,23.0,0.000000,0.0,0.0,0.0,1,1.0,60.0,...,0,0,0,0,0,0,0,0,0,0

In [27]:
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score

In [28]:
y = df['label']

In [29]:
X = df.drop(columns = ['label'])

In [31]:
y.sample(20)

1929493    1
91093      1
2987990    1
124940     1
7071       0
1709951    1
493112     1
3575105    1
1182435    1
84993      1
2086701    1
27980      1
128351     1
3783486    1
2982290    1
123999     1
210328     1
715082     1
1959237    1
278721     1
Name: label, dtype: int64

In [32]:
X.head()

,ts,id.orig_p,id.resp_p,duration,orig_bytes,resp_bytes,missed_bytes,history,orig_pkts,orig_ip_bytes,...,conn_state_S1,conn_state_S2,conn_state_S3,conn_state_SF,conn_state_SH,conn_state_SHR,service_dns,service_http,service_irc,service_ssh
0,1.525880e+09,51524.0,23.0,2.999051,0.0,0.0,0.0,1,3.0,180.0,...,0,0,0,0,0,0,0,0,0,0
1,1.525880e+09,56305.0,23.0,0.000000,0.0,0.0,0.0,1,1.0,60.0,...,0,0,0,0,0,0,0,0,0,0
2,1.525880e+09,41101.0,23.0,0.000000,0.0,0.0,0.0,1,1.0,60.0,...,0,0,0,0,0,0,0,0,0,0
3,1.525880e+09,60905.0,23.0,2.998796,0.0,0.0,0.0,1,3.0,180.0,...,0,0,0,0,0,0,0,0,0,0
4,1.525880e+09,44301.0,23.0,0.000000,0.0,0.0,0.0,1,1.0,60.0,...,0,0,0,0,0,0,0,0,0,0

In [33]:
del df

In [34]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [37]:
svm_classifier = LinearSVC(C=1.0)

In [39]:
from sklearn.preprocessing import StandardScaler

# Create a StandardScaler instance
scaler = StandardScaler()

# Fit the scaler on the training data and transform it
X_train_scaled = scaler.fit_transform(X_train)

# Transform the testing data using the same scaler
X_test_scaled = scaler.transform(X_test)

In [42]:
svm_classifier.fit(X_train_scaled,y_train)

C:\Users\Harshneel\anaconda3\Lib\site-packages\sklearn\svm\_classes.py:32: FutureWarning: The default value of `dual` will change from `True` to `'auto'` in 1.5. Set the value of `dual` explicitly to suppress the warning.
  warnings.warn(
C:\Users\Harshneel\anaconda3\Lib\site-packages\sklearn\svm\_base.py:1242: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

LinearSVC()

In [43]:
y_pred = svm_classifier.predict(X_test_scaled)

In [44]:
from sklearn.metrics import accuracy_score

In [46]:
accuracy = accuracy_score(y_test,y_pred)

In [47]:
accuracy

0.985838

In [48]:
from sklearn.metrics import classification_report

In [49]:
report = classification_report(y_test, y_pred)

In [50]:
print(report)

              precision    recall  f1-score   support

           0       0.94      0.96      0.95    142205
           1       0.99      0.99      0.99    857795

    accuracy                           0.99   1000000
   macro avg       0.97      0.97      0.97   1000000
weighted avg       0.99      0.99      0.99   1000000